lint:
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - .github/workflows/linting_comment.yml
  files_unchanged:
    - .gitattributes
    - .prettierignore
    - .github/PULL_REQUEST_TEMPLATE.md
  multiqc_config: false
  nf_test_content: false
nf_core_version: 4.1.0
repository_type: pipeline
template:
  author: Joon Klaps, Philippe Lemey, Liana Kafetzopoulou
  description: A bioinformatics best-practice analysis pipeline for untargeted viral
    genome reconstruction and to identify intra-host variants from metagenomic sequencing
    data.
  force: false
  is_nfcore: true
  name: viralmetagenome
  org: nf-core
  outdir: .
  skip_features:
    - igenomes
  version: 1.2.1dev
