lint:
  files_exist:
    - conf/test.config
    - conf/test_full.config
    - conf/igenomes.config
    - conf/igenomes_ignored.config
  multiqc_config: false
nf_core_version: 3.3.1
repository_type: pipeline
template:
  author: Joon Klaps, Philippe Lemey, Liana Kafetzopoulou
  description: a bioinformatics best-practice analysis pipeline for untargeted viral
    genome reconstruction and to identify intra-host variants from metagenomic sequencing
    data.
  force: false
  is_nfcore: true
  name: viralmetagenome
  org: nf-core
  outdir: .
  skip_features:
    - igenomes
    - multiqc
  version: 0.1.3dev
