# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: utils_nfcore_viralmetagenome_pipeline
description: Utility functions and pipeline initialization specific to the nf-core/viralmetagenome pipeline including parameter validation, sample sheet processing, and custom data manipulation functions
keywords:
  - utilities
  - pipeline initialization
  - parameter validation
  - sample sheet
  - data processing
  - helper functions
  - nf-core
components:
  - utils_nfschema_plugin
  - utils_nfcore_pipeline
  - utils_nextflow_pipeline
input:
  - version:
      description: |
        Pipeline version for initialization
        Type: string
  - validate_params:
      description: |
        Whether to validate pipeline parameters
        Type: boolean
  - logo:
      description: |
        Whether to display pipeline logo
        Type: boolean
  - citation:
      description: |
        Whether to display citation information
        Type: boolean
  - summary_params:
      description: |
        Parameter summary for display
        Type: map
  - hook_url:
      description: |
        Webhook URL for notifications
        Type: string
output:
  - versions:
      description: |
        Files containing software versions
        Structure: [ path(versions.yml) ]
authors:
  - "@Joon-Klaps"
maintainers:
  - "@Joon-Klaps"
