# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: bam_variants_ivar
description: Call variants from BAM files using iVar and convert to VCF format with filtering
keywords:
  - variant calling
  - ivar
  - bam
  - vcf
  - bcftools
  - filtering
  - variants
components:
  - ivar/variants
  - ivar_variants_to_vcf
  - ivar/variants/to/vcf
  - bcftools/sort
  - bcftools/filter
input:
  - ch_bam_fasta:
      description: |
        The input channel containing BAM files with their corresponding reference sequences
        Structure: [ val(meta), path(bam), path(fasta) ]
  - save_stats:
      type: boolean
      description: |
        Whether to save variant statistics (mpileup files)
output:
  - tsv:
      description: |
        Original iVar variant calls in TSV format
        Structure: [ val(meta), path(tsv) ]
  - vcf_orig:
      description: |
        Converted VCF files from iVar TSV output (unsorted)
        Structure: [ val(meta), path(vcf) ]
  - log_out:
      description: |
        Log files from iVar variants to VCF conversion
        Structure: [ val(meta), path(log) ]
  - multiqc:
      description: |
        MultiQC-compatible TSV files for quality control reporting
        Structure: [ val(meta), path(tsv) ]
  - vcf:
      description: |
        Sorted VCF files with variant calls
        Structure: [ val(meta), path(vcf) ]
  - vcf_filter:
      description: |
        Filtered VCF files with variant calls
        Structure: [ val(meta), path(vcf) ]
  - versions:
      description: |
        Files containing software versions
        Structure: [ path(versions.yml) ]
authors:
  - "@Joon-Klaps"
maintainers:
  - "@Joon-Klaps"
