# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: bam_deduplicate
description: Remove duplicates from BAM files using either UMI-based deduplication with UMI-tools or mark duplicates with Picard
keywords:
  - deduplication
  - bam
  - duplicates
  - umi
  - umitools
  - picard
  - markduplicates
  - samtools
components:
  - samtools/index
  - umitools/dedup
  - picard/markduplicates
input:
  - ch_bam_ref_fai:
      description: |
        The input channel containing BAM files with their corresponding reference sequences and index
        Structure: [ val(meta), path(bam), path(fasta), path(fai) ]
  - umi:
      type: boolean
      description: |
        Whether UMI-based deduplication should be used
  - mapping_stats:
      type: boolean
      description: |
        Whether to save mapping statistics and MultiQC files
output:
  - bam:
      description: |
        Deduplicated BAM files
        Structure: [ val(meta), path(bam) ]
  - mqc:
      description: |
        MultiQC files for quality control reporting (UMI-tools logs or Picard metrics)
        Structure: [ val(meta), path(mqc) ]
  - versions:
      description: |
        Files containing software versions
        Structure: [ path(versions.yml) ]
authors:
  - "@Joon-Klaps"
maintainers:
  - "@Joon-Klaps"
