# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: bam_stats_metrics
description: Generate comprehensive BAM file statistics and metrics using multiple tools for quality assessment
keywords:
  - bam
  - statistics
  - metrics
  - quality control
  - coverage
  - picard
  - mosdepth
  - samtools
  - mpileup
components:
  - samtools/index
  - picard/collectmultiplemetrics
  - mosdepth
  - bam_stats_samtools
  - custom/mpileup
  - custom_mpileup
input:
  - sort_bam_ref:
      description: |
        Sorted BAM files with their corresponding reference sequences
        Structure: [ val(meta), path(bam), path(ref) ]
output:
  - bai:
      description: |
        BAM index files
        Structure: [ val(meta), path(bai) ]
  - mqc:
      description: |
        MultiQC files containing various BAM statistics and metrics
        Structure: [ path(multiqc) ]
  - versions:
      description: |
        Files containing software versions
        Structure: [ path(versions.yml) ]
authors:
  - "@Joon-Klaps"
maintainers:
  - "@Joon-Klaps"
